Feature/fix makefile
groove-x/u-boot-xlnx pull request #7
Opened 2021-09-23 14:32 UTC by jnkbta

Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please
see https://www.denx.de/wiki/U-Boot/Patches

If your patch targets the Xilinx U-Boot repository please send a patch to git@xilinx.com.

2021-09-23 14:34 UTC, jnkbta commented
nosd用のファイル削除に対応できていない部分があったのでMakefile を修正しました。
デフォルトのsdbootdevを1にしました（デフォルトがSDのため。nosd用のファイルを生成するときにここを書き換えます。）

2021-09-24 02:25 UTC, ledmonster approved these changes

2021-09-24 05:04 UTC, ken-nakamura requested changes
コメントの通り、Makefile:L.339の修正が必要です。

2021-09-24 05:04 UTC, ken-nakamura commented on arch/arm/dts/Makefile
> +	zynqmp-jerry-nosd.dtb			\
L.339でzynqmp-jerry-nosd.dtbを動的に追加していますので、この修正を適用するには、L.339でzynqmp-jerry-nosd.dtbを動的に追加しない修正が必要です。

2021-09-24 05:04 UTC, ken-nakamura commented on arch/arm/dts/Makefile
> +	zynqmp-zc1751-xm019-dc5.dtb
BOARD_VENDOR=gxをサポートしないのであれば、問題ありません。

2021-09-24 07:38 UTC, ken-nakamura approved these changes

2021-09-24 07:38 UTC, merged